# Generated by Django 5.0.4 on 2024-07-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Osoby',
            fields=[
                ('id_osoby', models.SmallAutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=20)),
                ('kod_osoby', models.CharField(max_length=3)),
                ('telefon', models.CharField(blank=True, max_length=15, null=True)),
                ('mail', models.CharField(max_length=50)),
                ('płeć', models.CharField(blank=True, max_length=1, null=True)),
                ('kraj_pochodzenia', models.CharField(blank=True, max_length=30, null=True)),
                ('cecha_charakterystyczna', models.CharField(blank=True, max_length=50, null=True)),
                ('uwagi', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'osoby',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
