# Generated by Django 5.0.4 on 2024-07-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Families',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'families',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FamiliesAdv',
            fields=[
                ('pid', models.IntegerField(db_column='pid', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'families_id',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('pid', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('pcode', models.CharField(max_length=3)),
                ('phone_nr', models.CharField(blank=True, max_length=15, null=True)),
                ('mail', models.CharField(max_length=50)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('country_code', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'people',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Osoby',
        ),
        migrations.DeleteModel(
            name='Rodziny',
        ),
    ]
