# Generated by Django 5.0.4 on 2024-07-28 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_families_familiesadv_people_delete_osoby_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FamiliesAdv',
        ),
    ]
