# Generated by Django 5.0.4 on 2024-09-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_delete_familiesadv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('rid', models.SmallAutoField(db_column='rid', primary_key=True, serialize=False)),
                ('role_name', models.CharField(db_column='role_name', max_length=50, verbose_name='Nazwa roli')),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
    ]
