# Generated by Django 5.0.4 on 2024-09-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleRoles',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'people_roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('prid', models.SmallAutoField(db_column='prid', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=50, verbose_name='')),
                ('description', models.CharField(db_column='description', max_length=200, null=True, verbose_name='')),
            ],
            options={
                'db_table': 'projects',
                'managed': False,
            },
        ),
    ]
