# Generated by Django 5.0.4 on 2024-11-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_activities_activitytypes_attendance_codes_consents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceTypes',
            fields=[
                ('id', models.SmallAutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=20, unique=True)),
            ],
            options={
                'db_table': 'attendance_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Attendees',
            fields=[
                ('id', models.IntegerField(db_column='dummy', default=1, primary_key=True, serialize=False)),
                ('no_attendees', models.IntegerField(db_column='no_atendees', verbose_name='Liczba uczestników')),
            ],
            options={
                'db_table': 'view_atendees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SelectAttendees',
            fields=[
                ('category', models.CharField(db_column='category', primary_key=True, serialize=False)),
                ('no_attendees', models.IntegerField(db_column='no_atendees')),
            ],
            options={
                'db_table': 'select_atendees',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Atendees',
        ),
        migrations.DeleteModel(
            name='SelectAtendees',
        ),
    ]
