# Generated by Django 5.0.4 on 2024-11-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleEvents',
            fields=[
                ('id', models.IntegerField(db_column='dummy', default=1, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'view_people_events',
                'managed': False,
            },
        ),
    ]
