# Generated by Django 5.0.4 on 2024-11-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.SmallAutoField(db_column='id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'test',
                'managed': False,
            },
        ),
    ]
