# Generated by Django 5.0.4 on 2024-11-19 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
