# Generated by Django 4.2.17 on 2025-03-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genders',
            fields=[
                ('id', models.SmallAutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=20, unique=True)),
            ],
            options={
                'db_table': 'genders',
                'managed': False,
            },
        ),
    ]
