# Generated by Django 4.2.17 on 2025-04-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_genders'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMembers',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=50, unique=True, verbose_name='Nazwa')),
            ],
            options={
                'db_table': 'family_members',
                'managed': False,
            },
        ),
    ]
