# Generated by Django 4.2.17 on 2025-04-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_familymembers'),
    ]

    operations = [
        migrations.CreateModel(
            name='GRAT',
            fields=[
                ('id', models.IntegerField(db_column='dummy', default=1, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'view_atendees',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='attendees',
            table='atendees',
        ),
    ]
